name: Python Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e "DataManagement[dev]"

    - name: Lint with flake8
      run: |
        flake8 DataManagement/airglow DataManagement/dagster/ --count --select=E9,F63,F7,F82 --show-source --statistics 

    - name: Test with pytest
      working-directory: DataManagement/tests
      run: |
        pytest

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Set up QEMU
      if: github.event_name == 'push'
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      if: github.event_name == 'push'
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Air Glow dagster project
      if: github.event_name == 'push'
      uses: docker/build-push-action@v4
      with:
        context: ./DataManagement/dagster
        file: ./DataManagement/dagster/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/airglowrsss/dagster-airglow:${{ env.branch }}
